title: Krishna Bhatt
logo: /assests/img/headshot.png
description: Hi! My name is Krishna. In my natural habitat, you'll probably find me working on a puzzle that's bugging me, from deciphering cortical dynamics from EEG data to constructing balancing devices for Parkinson's patients. 
theme: jekyll-theme-minimal
